language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    
cache: cargo

before_script:
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    rustup component add clippy;
    rustup component add rustfmt;
  fi

script:
  - cargo build
  - cargo test -- --test-threads=1
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then 
      cargo fmt -- --check;
    fi
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then 
      cargo clippy --all-targets --all-features -- -D warnings;
    fi
